// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3ghx7gfpGr35izdQGe6d7VCh5juHkypo',
    appId: '1:131437904837:web:4383b92ff8898b3d0101ac',
    messagingSenderId: '131437904837',
    projectId: 'fooddeliveryapp-c0b0a',
    authDomain: 'fooddeliveryapp-c0b0a.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-c0b0a.appspot.com',
    measurementId: 'G-ECHDBS04XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT6Pb26cHtDhHAhsz2WydhVX8qJG7J-ww',
    appId: '1:131437904837:android:5715b58495a063a30101ac',
    messagingSenderId: '131437904837',
    projectId: 'fooddeliveryapp-c0b0a',
    storageBucket: 'fooddeliveryapp-c0b0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOTgotTgndCkMirjrkGQx5gPCltIZdH6M',
    appId: '1:131437904837:ios:5223d6d0a05321480101ac',
    messagingSenderId: '131437904837',
    projectId: 'fooddeliveryapp-c0b0a',
    storageBucket: 'fooddeliveryapp-c0b0a.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOTgotTgndCkMirjrkGQx5gPCltIZdH6M',
    appId: '1:131437904837:ios:5223d6d0a05321480101ac',
    messagingSenderId: '131437904837',
    projectId: 'fooddeliveryapp-c0b0a',
    storageBucket: 'fooddeliveryapp-c0b0a.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3ghx7gfpGr35izdQGe6d7VCh5juHkypo',
    appId: '1:131437904837:web:e2c802da9ee73b170101ac',
    messagingSenderId: '131437904837',
    projectId: 'fooddeliveryapp-c0b0a',
    authDomain: 'fooddeliveryapp-c0b0a.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-c0b0a.appspot.com',
    measurementId: 'G-EF1H96L8J8',
  );
}
